[workspace]
members = [
    "crypto-ingestor",
    "canonicalizer",
    "analytics",
    "on-chain",
    "signals",
    "onchain-ingestor",
    "macro-data",
]
resolver = "2"

[profile.release]
opt-level = 3
